### ISSUE TITLE
Python 7.7 version could not be supported anymore

### ISSUE THREAD

**Issue by Sherzadd** [pymanga/pyMANGA#325]
**Hello,** 
As, Python 3.7.7 has been reached to the end-of-life and could not be supported anymore. Is there any solution to run Pymanga setup using the latest version of Python? Please see the attached screenshot. 
<img width="930" alt="Screenshot 2024-02-15 103118" src="https://github.com/pymanga/pyMANGA/assets/143507506/80db0fcc-46f6-4b99-9ff1-bfda2369d4a5">

**Comment by rbnmj** [comment]
Hi Sherzadd, 
from our current understanding pyMANGA is running without issues on the newest release python 3.12.2.
There might by issues with ogs, in particular because the package vtk 9.2.2 is not available for python 3.12. However, we tested the latest vtk version and so far did not run into problems.
